### ISSUE TITLE
todo Model

### ISSUE THREAD

**Issue by jeffgrasso42** [jeffgrasso42/vintage_todo_list#18]
- [ ] write some seeds
- [ ] write a seed script that creates todos, relates them to users
- [ ] write a model that makes seeds work
- [ ] write a relationship between users and todos

**Comment by jeffgrasso42** [comment]
- [ ] write some seeds
- [ ] write a seed script that creates todos, relates them to users
- [ ] write a model that makes seeds work
- [ ] write a relationship between users and todos
